name: Deploy one instance per feature

on:
  push:
    branches:
      - '*feature*'

env:
  IMAGE_NAME: ${{ github.repository }}:${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build n Push
        run: |
          docker build . -t ${{ env.IMAGE_NAME }} -f "./3. avanzado/Dockerfile"
          docker push ${{ env.IMAGE_NAME }}

      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
          image: ghcr.io/${{ env.IMAGE_NAME }}
          name: ${{ env.IMAGE_NAME }}
          location: 'eastus2'

      - name: Get instance url
        run: echo "${{ steps.deploy.outputs.app-url }}"
